### PR TITLE
Default to the default shell

### PR DESCRIPTION
**Pull request by lunaryorn**
Use `$SHELL` by default, and fall back to `/bin/bash`.

### CODE REVIEW

**Comment by syohex** [comment]
I suppose `shell-file-name` variable is better than `(getenv "SHELL")`. How about you ?

**Comment by lunaryorn** [comment]
I didn't know about `shell-file-name`.  It seems to be the appropriate thing to use.

**Comment by lunaryorn** [comment]
Updated this PR accordingly.

**Comment by syohex** [comment]
Thanks

**Pull request merged**
