### PR TITLE
Fix bugs about hook

### PR DESCRIPTION
**Pull request by xlighting**

### CODE REVIEW

**Comment by syohex** [comment]
What about **bug** ? Could you explain it to us ?

**Comment by xlighting** [comment]
See the file changed

**Comment by xlighting** [comment]
my config
 `(add-hook 'shell-pop-**in**-hook (lambda () (setq-local helm-split-window-default-side 'right)))`
dosen't work , and then I found something  wrong in shell-pop.el

**Comment by syohex** [comment]
Oh, there is typo.

However why did you change point where hooks are called ?

**Comment by xlighting** [comment]
Oh,.................
because my config
````emacs-lisp
(add-hook 'shell-pop-in-hook (lambda () (setq-local helm-split-window-default-side 'right)))
````
doesn't work as expected

**Comment by syohex** [comment]
> Oh, there is typo.

Sorry this means `shell-pop-up-hook` -> `shell-pop-in-hook` in original code.

**Comment by xlighting** [comment]
Ok,
Can you add  a shell-pop-after-in-hook (may be other name)

**Comment by syohex** [comment]
> Can you add a shell-pop-after-in-hook (may be other name)

Yes, will do. Please wait.

**Comment by xlighting** [comment]
Thanks

**Pull request closed without merging**
